### ISSUE TITLE
Doesn't display page numbers, when  print

### ISSUE THREAD

**Issue by yunushkin88** [dimkanovikov/PagesTextEdit#4]
Hi @dimkanovikov
Page numbers in the PagesTextEdit project are displayed perfectly, which is cool, but when I try to print a document in the output file, I usually do it .pdf doesn't display page numbers, how can fix it?

**Comment by dimkanovikov** [comment]
Hello. Since in this implementation page numbers not a part of the document, but just a sort of decoration, you need to implement page numbers painting for PDF manually. Here you can find an example of how to do it manually here https://github.com/dimkanovikov/KITScenaristCore/blob/develop/BusinessLayer/Export/PdfExporter.cpp

**Comment by yunushkin88** [comment]
Thanks for the answer. Do I understand correctly that in General, in Qt, you can only go this way if you need to set and print the page number in any place on the page? There is nothing more native to Qt (maybe some functions)?

**Comment by dimkanovikov** [comment]
I don't know another way of how to print page numbers to pdf with Qt.
